### ISSUE TITLE
Fell through the level

### ISSUE THREAD

**Issue by jpettis** [egingric/2016-Racing-Game#10]
I somehow fell through the landscape when I missed the landing on the stunt; I'm not sure what happened. Maybe it is a collision issue?

![feedbackamelia](https://cloud.githubusercontent.com/assets/18125486/14190532/54ec5d26-f761-11e5-9cb4-14360a9d3cda.JPG)

**Comment by ameliamarch** [comment]
Added more kill triggers to prevent this from happening
