### ISSUE TITLE
LAVA MAN

### ISSUE THREAD

**Issue by Msulliv2** [egingric/2016-Racing-Game#104]
I can drive ON FIREEEE. Make that stuff like REALLY deadly, add a kill volume around the puddle so we can't head so far off into the lava wonderland. 
![seth1](https://cloud.githubusercontent.com/assets/18143256/14210017/1a7b4f96-f7f5-11e5-8190-021f80754ae1.JPG)

**Comment by sbaldwi1** [comment]
It has been fixed
