### ISSUE TITLE
lighting errors

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#131]
Warning: Cached component instance data transform did not match!  Discarding cached lighting data which will cause lighting to be unbuilt. 

Rock_pile16.StaticMesh7 

Current X=39539.527344 Y=-34702.210938 Z=4784.662598 Cached X=39539.527344 Y=-34702.207031 Z=4784.662598

**Comment by ameliamarch** [comment]
Lighting errors no longer present
