### ISSUE TITLE
BoR Issues: Hailey Williams

### ISSUE THREAD

**Issue by scarrollrcad** [egingric/2016-Racing-Game#136]
- [x] additional set dressing / mechanics interior pipes (industrial barrel)
- [x] work on road to mitigate tiling
- [x] lighten up interior ship
- [X] rampway feasability - holes
- [X] find public domain assets to use
- [X] add music
- [ ] more gameplay elements to experience and visual variety (Falling crates)

**Comment by hwilliamgad** [comment]
Music has been added. Sparks with sound added in ship interior. Changed the scale in the spline settings to fix ramp feasability. Remodeled the Sewer Pipes and did another material pass on them. 

Collected Assets (with permission from the respective owners) and have begun setdressing.

**Comment by hwilliamgad** [comment]
Able to incorporate everything except scripted/gameplay events
