### ISSUE TITLE
Too Many Polys

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#153]
I know I said Polys were one of the least important things to worry about as far as frame rate goes but there is a limit to how far you can take this. I can't even see through your meshes, road, rocks on the side (rail) and your bones, in wireframe mode. You could probably get away with reducing these without a loss of fidelity. The game has to run at frame rate in 4 player split screen for Best Of Ringling. Not sure if your does at the moment.

![ameliatoodense](https://cloud.githubusercontent.com/assets/3945065/14234882/449c7e80-f9bc-11e5-81f0-e62a9559afb9.PNG)

**Comment by ameliamarch** [comment]
Replaced some of the higher poly rocks with lower poly meshes, removed tessellated geometry from the landscape (yikes) and road splines. Last I checked, 4 player mode worked fine in 322.
