### ISSUE TITLE
Respawning Issue

### ISSUE THREAD

**Issue by csammart** [egingric/2016-Racing-Game#169]
Got stuck on the railing, forcing me to respawn to get unstuck- but I didn't respawn at all. Not sure if it was an issue with your checkpoint respawn or what. It's by the initial cave entrance on the left side. 

@Msulliv2

**Comment by Msulliv2** [comment]
@csammart 
I may need your help recreating this.

**Comment by csammart** [comment]
Ask Jess, she found the error!  I was reporting it for her.
Best of luck
On Monday, April 4, 2016, Miles Sullivan notifications@github.com wrote:

> @csammart https://github.com/csammart
> I may need your help recreating this.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/egingric/2016-Racing-Game/issues/169#issuecomment-205630091

## 

Cassandra Sammartano
Game & Graphic Designer
(631)418-7335
csammart@c.ringling.edu
