### ISSUE TITLE
Texture/Possible Lightmap issues -- Jessica

### ISSUE THREAD

**Issue by ameliamarch** [egingric/2016-Racing-Game#18]
No textures on the road -- also it looks like there's a lightmap issue from this screenshot
![jessica_road](https://cloud.githubusercontent.com/assets/18125563/14191058/efd21a4a-f763-11e5-80d2-ab8db6b28f48.PNG)

**Comment by jbiglin** [comment]
Fixed this, my material sources were just screwed up!
