### ISSUE TITLE
Bank your turns 

### ISSUE THREAD

**Issue by csammart** [egingric/2016-Racing-Game#196]
A little too difficult to drive on.

**Comment by diosmiodio** [comment]
were you playing on standalone or preview? Trying to narrow down the issue with collision & spline. Thanks.

**Comment by csammart** [comment]
Standalone. I was taking bugs for four classmates playing it at a time.

On Monday, April 4, 2016, Dionisio Blanco notifications@github.com wrote:

> were you playing on standalone or preview? Trying to narrow down the issue
> with collision & spline. Thanks.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/egingric/2016-Racing-Game/issues/196#issuecomment-205622246

## 

Cassandra Sammartano
Game & Graphic Designer
(631)418-7335
csammart@c.ringling.edu

**Comment by diosmiodio** [comment]
Ah alright cool. Did u run into any random collision issues with the spline
or is that just me? (With smaller cars)

Regards,
Dionisio Blanco
dionisioblanco3d.com

Sent from my iPhone

On Apr 5, 2016, at 1:47 AM, csammart notifications@github.com wrote:

Standalone. I was taking bugs for four classmates playing it at a time.

On Monday, April 4, 2016, Dionisio Blanco notifications@github.com wrote:

> were you playing on standalone or preview? Trying to narrow down the issue
> with collision & spline. Thanks.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <
> https://github.com/egingric/2016-Racing-Game/issues/196#issuecomment-205622246

## 

Cassandra Sammartano
Game & Graphic Designer
(631)418-7335
csammart@c.ringling.edu

**Comment by csammart** [comment]
No collision issues, just bumps here and there. The transition from the
road bottom to the sides could be smoother as well. Hope that helps!

On Tue, Apr 5, 2016 at 2:39 AM, Dionisio Blanco notifications@github.com
wrote:

> Ah alright cool. Did u run into any random collision issues with the spline
> or is that just me? (With smaller cars)
> 
> Regards,
> Dionisio Blanco
> dionisioblanco3d.com
> 
> Sent from my iPhone
> 
> On Apr 5, 2016, at 1:47 AM, csammart notifications@github.com wrote:
> 
> Standalone. I was taking bugs for four classmates playing it at a time.
> 
> On Monday, April 4, 2016, Dionisio Blanco notifications@github.com
> wrote:
> 
> > were you playing on standalone or preview? Trying to narrow down the
> > issue
> > with collision & spline. Thanks.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> 
> https://github.com/egingric/2016-Racing-Game/issues/196#issuecomment-205622246
> 
> 
> ## 
> 
> Cassandra Sammartano
> Game & Graphic Designer
> (631)418-7335
> csammart@c.ringling.edu
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <
> https://github.com/egingric/2016-Racing-Game/issues/196#issuecomment-205656023
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/egingric/2016-Racing-Game/issues/196#issuecomment-205674892

## 

Cassandra Sammartano
Game & Graphic Designer
(631)418-7335
csammart@c.ringling.edu

**Comment by diosmiodio** [comment]
Yup it does! Thank you!

Regards,
Dionisio Blanco
dionisioblanco3d.com

Sent from my iPhone

On Apr 5, 2016, at 12:37 PM, csammart notifications@github.com wrote:

No collision issues, just bumps here and there. The transition from the
road bottom to the sides could be smoother as well. Hope that helps!

On Tue, Apr 5, 2016 at 2:39 AM, Dionisio Blanco notifications@github.com
wrote:

> Ah alright cool. Did u run into any random collision issues with the
> spline
> or is that just me? (With smaller cars)
> 
> Regards,
> Dionisio Blanco
> dionisioblanco3d.com
> 
> Sent from my iPhone
> 
> On Apr 5, 2016, at 1:47 AM, csammart notifications@github.com wrote:
> 
> Standalone. I was taking bugs for four classmates playing it at a time.
> 
> On Monday, April 4, 2016, Dionisio Blanco notifications@github.com
> wrote:
> 
> > were you playing on standalone or preview? Trying to narrow down the
> > issue
> > with collision & spline. Thanks.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> 
> https://github.com/egingric/2016-Racing-Game/issues/196#issuecomment-205622246
> 
> 
> ## 
> 
> Cassandra Sammartano
> Game & Graphic Designer
> (631)418-7335
> csammart@c.ringling.edu
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <
> 
> https://github.com/egingric/2016-Racing-Game/issues/196#issuecomment-205656023
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <
> https://github.com/egingric/2016-Racing-Game/issues/196#issuecomment-205674892

## 

Cassandra Sammartano
Game & Graphic Designer
(631)418-7335
csammart@c.ringling.edu

**Comment by diosmiodio** [comment]
banked them a bit but in some areas it'll break the collision of the spline. did my best with the allotted time for BoR atm
