### ISSUE TITLE
Why isn't this in your level?

### ISSUE THREAD

**Issue by nclark1** [egingric/2016-Racing-Game#221]
[](http://www.anynewsbd.com/images/flying-serpent.jpg)

**Comment by ameliamarch** [comment]
Why isn't what in my level?

**Comment by ameliamarch** [comment]
Uh remind me again what this was lol

**Comment by nclark1** [comment]
It was the flying serpent

**Comment by ameliamarch** [comment]
Can I just have my 3D Character flying through the sky???

But yeah no, resubmit milestone for sure.

**Comment by nclark1** [comment]
Why isn't this closed? D:
