### ISSUE TITLE
Invisible collision

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#235]
Stops me on 
![dio invisible collision](https://cloud.githubusercontent.com/assets/3945065/14317318/b6ce0da0-fbd5-11e5-9103-8fd1b1f8095f.PNG)
your track

**Comment by egingric** [comment]
Whatever the grey sphere is.

**Comment by diosmiodio** [comment]
fixed. will be updating perforce when lighting builds.

**Comment by egingric** [comment]
Still invisible collision problems on your track.
![diocollision](https://cloud.githubusercontent.com/assets/3945065/14336390/575b6df2-fc31-11e5-9afa-873a9127e68b.PNG)
@shong1123

Another one:
![diocollision2](https://cloud.githubusercontent.com/assets/3945065/14336443/1637c28e-fc32-11e5-991b-ef7eb8d55881.PNG)

**Comment by diosmiodio** [comment]
would have fixed it tonight if unreal would have shown my project file.. Ill get to it first thing in the morning. I don't think thats a rock thats actually a collision box on the track that for some reason broke there. I'll check it out ASAP.

**Comment by diosmiodio** [comment]
Checked it back in. Shouldn't be there anymore. I didn't realize it had player collision sorry!

**Comment by scarrollrcad** [comment]
1
