### ISSUE TITLE
Reduce Landscape Density of Polys?

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#237]
Can you try reducing your landscape polys down by about 75%? May help frame rate.

**Comment by ameliamarch** [comment]
I removed tessellation from my landscape last night --- not sure how it got tessellated in the first place but that was what we were seeing in wireframe mode. Also removed rock collisions outside of my road/replaced some of my higher poly rock meshes/removed tess from my road spline. Is the frame rate still low today?

**Comment by egingric** [comment]
Actually, I didn't your latest. Let me check!

**Comment by ameliamarch** [comment]
Fixed
