### ISSUE TITLE
More Errors For Tahoe

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#248]
Open each of these materials and check to see if the flag UsedWithStaticLighting is checked. If not, check this box on, then no matter w, check the material in to fix this error.

M_tbautist_lightpole missing bUsedWithStaticLighting=True! 
M_tbautist_lightpoleglasslight. missing bUsedWithStaticLighting=True!
M_pipe2_texture.M_pipe2_texture missing bUsedWithStaticLighting=True! 
tbautist_glassbuilding missing bUsedWithStaticLighting=True!
M_tbautist_building1 missing bUsedWithStaticLighting=True! 
     The material will recompile every editor launch until resaved.
M_tbautist_bridgespline2 missing bUsedWithStaticLighting=True! 
     The material will recompile every editor launch until resaved.
M_tbautist_sakesign missing bUsedWithStaticLighting=True! Default Material will be used in game.
     The material will recompile every editor launch until resaved.
M_tbautist_building5 missing bUsedWithStaticLighting=True! Default Material will be used in game.
     The material will recompile every editor launch until resaved.
M_building6ice missing bUsedWithStaticLighting=True! Default Material will be used in game.
     The material will recompile every editor launch until resaved.
Material /Game/GA228/02/tbautist/tbauist_props/building/building7M_Tbautist_building7 missing bUsedWithStaticLighting=True! Default Material will be used in game.
     The material will recompile every editor launch until resaved.
M_tbautist_greentea missing bUsedWithStaticLighting=True! Default Material will be used in game.
     The material will recompile every editor launch until resaved.
M_tbautist_otakuposter missing bUsedWithStaticLighting=True! Default Material will be used in game.
     The material will recompile every editor launch until resaved.
M-tbautistmetaltracks missing bUsedWithStaticLighting=True! Default Material will be used in game.
     The material will recompile every editor launch until resaved.
M_tbautist_tracklines missing bUsedWithStaticLighting=True! Default Material will be used in game.
     The material will recompile every editor launch until resaved.
M_tbautist_metaltrackdetails missing bUsedWithStaticLighting=True! Default Material will be used in game.
     The material will recompile every editor launch until resaved.
M_tbautist_sushisign missing bUsedWithStaticLighting=True! Default Material will be used in game.
     The material will recompile every editor launch until resaved.
M_tbautist_wavesign missing bUsedWithStaticLighting=True! Default Material will be used in game.

@msotolon  Are you using these?

**Comment by msotolon** [comment]
fixed
