### ISSUE TITLE
Turret in your level ?!?!?!

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#255]
![wtf is this doing in your level](https://cloud.githubusercontent.com/assets/3945065/14372378/03060144-fd0e-11e5-9b41-f9b8b46a0f4b.PNG)
WHY? Remove it! Yesterday!

**Comment by sbaldwi1** [comment]
Oh shit that was for testing my hud. I'm not able to remove it but I'll
text Michael and ask him to. Sorry about that.

**Comment by mfilipek** [comment]
I removed it an checked it in
