### ISSUE TITLE
Seth - Sampler type is Color, should be Linear Color Error

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#260]
These errors are still here:
Failed to compile Material /Game/Assets/Vehicles/sbaldwinGhibli/CarHUD/HudArtwork/Sbaldwin_RPMMeterMatty.Sbaldwin_RPMMeterMatty for platform PCD3D_SM5, Default Material will be used in game.
     (Node TextureSample) TextureSample> Sampler type is Color, should be Linear Color for /Game/Assets/Vehicles/sbaldwinGhibli/CarHUD/HudArtwork/Sbaldwin_RPMAlpha.Sbaldwin_RPMAlpha

**Comment by sbaldwi1** [comment]
fixed
