### ISSUE TITLE
Seth's Starter Content - 01

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#263]
Hi Seth. Looks like you have checked starter content into the racing game in the following location:

\Content\GA240\01\sbaldwin\Ch7_Barrel\StarterContent

This is not OK for two reasons, 1)  Scott (@scarrollrcad) and I specifically try to only check in the smallest possible amount of unreal example content as possible to keep the size of our game down, and 2) Because we specifically asked you guys not to use Unreal assets in the shipping game. We are representing this as our own art that we created ourselves, which can get all of us into all sorts of trouble.

I was about to ask you to delete it all, (DON"T YET) but for fun, I ran the reference viewer on it, and several students - @hwilliamgad  @zwang0930 @pvarney1 @msotolon  and @vbaguiro @crwrosilie @qoverbay - are using assets from your starter content folder. 

We need all you guys to switch out these references to use your own content that you created yourselves, ASAP. Then, and only then, can we delete the folder.

Please use these screenshots from the reference viewer below to help you find the offending references
![sethstartercontentreferences1](https://cloud.githubusercontent.com/assets/3945065/14776494/f3c8527e-0a94-11e6-9646-8a2ed38ed87d.PNG)
![sethstartercontentreferences2](https://cloud.githubusercontent.com/assets/3945065/14776496/f3c99cb0-0a94-11e6-889c-00be50bb5f84.PNG)
![sethstartercontentreferences3](https://cloud.githubusercontent.com/assets/3945065/14776495/f3c97e56-0a94-11e6-9306-34065569e407.PNG)

**Comment by egingric** [comment]
It's been 3 days and several of you have done anything about this issue. Need to see something happening here. Feedback as to why you have not done anything or immediate action.

@sbaldwi1  @hwilliamgad @pvarney1 @msotolon and @vbaguiro @crwrosilie - are still using assets from this starter content folder. These are Unreal assets, you cannot use these.

**We need all you guys to switch out these references to use your own content that you created yourselves, ASAP. Then, delete the folder.**

**Comment by egingric** [comment]
So, since @hwilliamgad didn't update her stuff yet we are getting errors now

Can't find file for asset '/Game/GA240/01/sbaldwin/Ch7_Barrel/StarterContent/Materials/M_Basic_Wall' while loading /Content/GA240/01/hwilliam/CH08_Weapon/Particles/P_hwilliam_shells.uasset.

Can't find file for asset '/Game/GA240/01/sbaldwin/Ch7_Barrel/StarterContent/Shapes/Shape_Pipe' while loading /Content/GA240/01/hwilliam/CH08_Weapon/Particles/P_hwilliam_shells.uasset.

@hwilliamgad Please fix

**Comment by hwilliamgad** [comment]
I'm in class right now but I'll address it as soon as I'm out of crit
