### ISSUE TITLE
Seth's Starter Content - 02

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#264]
Seth, Looks like you checked another starter content folder. 

\Content\GA240\01\sbaldwin\Ch7_Barrel\SbaldwiCh7BarrelMap\Content\StarterContent

I ran the reference viewer on it and it appears @rmaxwell0016 @vbaguiro are also using assets from this location. 

Everyone please clean these up to use only content created by us, otherwise we will get into a lot of trouble for representing this as art we created ourselves.

Here are some screenshots from the reference viewer to help you track these down
![sethstartercontent02references1](https://cloud.githubusercontent.com/assets/3945065/14777026/4fd7e162-0a98-11e6-8299-d13494f2353c.PNG)
![sethstartercontent02references2](https://cloud.githubusercontent.com/assets/3945065/14777029/4fdbcaf2-0a98-11e6-94c4-ea1d14e83ed6.PNG)
![sethstartercontent02references3](https://cloud.githubusercontent.com/assets/3945065/14777027/4fd86f88-0a98-11e6-9852-01cf14f13510.PNG)

(@scarrollrcad fyi)

**Comment by egingric** [comment]
It's been 3 days and NONE of you have done anything about this issue. Need to see something happening here. Feedback as to why you have not done anything or immediate action.

@sbaldwi1 @rmaxwell0016  and @vbaguiro - are still using assets from this starter content folder. These are Unreal assets, you cannot use these.

We need all you guys to switch out these references to use your own content that you created yourselves, ASAP. Then, delete the folder.

**Comment by sbaldwi1** [comment]
I have fixed my particles and mats referencing stuff from the starter
content folders and deleted them
