### ISSUE TITLE
Filenames too long to package -Seth

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#265]
Do mind reducing the path to and size of these filenames by about a hundred characters for me?

PackagingResults:Error: filename is too long: /Content/GA228/02/Sbaldwin/Baldwin_RaceTrackAssets/BuildingModules/BuildingModuleMaterial/M_Sbaldwin_BuildingModuleMat2_COlor3.uasset

Couldn't save package, filename is too long: /Content/GA228/02/Sbaldwin/Baldwin_RaceTrackAssets/BuildingModules/BuildingModuleMaterial/M_Sbaldwin_BuildingModuleMat2_COlor2.uasset

**Comment by sbaldwi1** [comment]
It is hidden

**Comment by sbaldwi1** [comment]
it hath been shortened. Thy will be done my liege.
