### ISSUE TITLE
Can't find Weapon - Miles

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#277]
Can't find file '/Game/Weapons/Msulliv_Weapon/Msulliv2_Weapon'

**Comment by Msulliv2** [comment]
There doesn't seem to be a problem on my end with this. I reimported/checked back in to be safe. 

@egingric

**Comment by Msulliv2** [comment]
Apparently it was referencing something with a similar name that never existed to something that doesn't exist anymore. I think I fixed it. 
@egingric
