### ISSUE TITLE
Flat buildings

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#287]
When I suggested that some buildings could just be images, I meant that these would be so far away that you couldn't tell. Not right next to the track. Please move these to the distance.
![chandlerflatbuildings](https://cloud.githubusercontent.com/assets/3945065/14858886/bff258fa-0c6f-11e6-92e5-e07cd041c03e.PNG)

**Comment by ghost** [comment]
Moved back, edited also in photoshop
