### ISSUE TITLE
Road Issues - Chandler

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#289]
Your road has several things about it that don't seem like they would match a real - world reference. The Jersey barrier "rails" are spaced in a way that they would never be in real life (due to gaps cars would run into them and stop rather than glancing off). Your road surface has strong sharp elevation changes which don't match any known road construction that Ive seen. Cars would constantly bump and be unable to drive on these. Your "median" is a bunch of disconnected CG looking blocks. Seems like a median would be continuous unless there was a cross street.

![roadissueschandler](https://cloud.githubusercontent.com/assets/3945065/14859307/974b2da8-0c71-11e6-9423-648441376951.PNG)

**Comment by ghost** [comment]
fixed
