### ISSUE TITLE
jpettis destructible bars

### ISSUE THREAD

**Issue by ameliamarch** [egingric/2016-Racing-Game#34]
The bars don't look like something you can drive through
![jpettis_bars](https://cloud.githubusercontent.com/assets/18125563/14191616/bf0bee60-f766-11e5-9a3c-78c3857bda45.PNG)

**Comment by ameliamarch** [comment]
Perhaps make them cracked & broken looking?

**Comment by jpettis** [comment]
I made another one of these assets with some of the bars in the gate missing to make it look like it's been broken already. I may do more to it to make them look cracked and rusted!
