### ISSUE TITLE
Racing Track Railing Aesthetic

### ISSUE THREAD

**Issue by csammart** [egingric/2016-Racing-Game#38]
![jamisha2](https://cloud.githubusercontent.com/assets/18124673/14191677/4210849c-f767-11e5-95b8-d90fbc94d7b0.png)
It doesn't really make sense theme wise to have railing like that indoors. Maybe have a flat road mesh without railing for the indoors since there is wall borders anyway. Also it's too shiny.

**Comment by jpettis** [comment]
I changed the road meshes on the inside of the castle to have no rails; I also made the metal on the railing a lot less shiny.
