### ISSUE TITLE
Fall through world

### ISSUE THREAD

**Issue by jbiglin** [egingric/2016-Racing-Game#41]
@msotolon There's a spot right after the tunnel ends, if you take the non-tunnel route and crash against that wire structure, you'll flip over and fall through the track! I think eric said to fix the collision on your track itself.

![mauricio](https://cloud.githubusercontent.com/assets/17817702/14191890/55b68aea-f768-11e5-9c0d-b3b245b8015f.PNG)

**Comment by msotolon** [comment]
B bug forsur, thanks !! :)
