### ISSUE TITLE
Tunnel Enhancement 

### ISSUE THREAD

**Issue by csammart** [egingric/2016-Racing-Game#42]
Some color mixing would look really cool instead of the same ice blue thats in the lights and tunnel material color. So, some differnt degrees of blue in the tunnel to add some richness. 

![jamisha2](https://cloud.githubusercontent.com/assets/18124673/14191895/585a88fa-f768-11e5-8dea-cf7e838f995c.png)

**Comment by msotolon** [comment]
did it
