### ISSUE TITLE
Dont let me roll down the hill

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#59]
This is YUGE! I said this before, listen to me now, hear me later, don't let players roll down a hill at the start of the game.
![seth1](https://cloud.githubusercontent.com/assets/3945065/14208377/09deeace-f7ed-11e5-89f7-58a8e00fe804.PNG)

**Comment by egingric** [comment]
@schung2 Oh, and fix that planet in the background, Don't want to see the polygons like it's 2004!

**Comment by schung2** [comment]
@egingric  Thats not my planet. snap!

**Comment by egingric** [comment]
Oh you are right. I will make a new bug for that.

**Comment by sbaldwi1** [comment]
fixed this a while ago.
