### ISSUE TITLE
Lighting on trees

### ISSUE THREAD

**Issue by brouth** [egingric/2016-Racing-Game#76]
They seem to be one shape because the trees don't have light maps. Maybe put in a BP of a fire and a point light in there to give off more light
![chandler](https://cloud.githubusercontent.com/assets/18143258/14209258/3775da52-f7f1-11e5-8d68-d5c2e9867f99.JPG)

**Comment by ghost** [comment]
added some lights around to highlight some, but couldn't afford to have them entirely lit because of performance and memory
