### ISSUE TITLE
Kind of confusing path

### ISSUE THREAD

**Issue by Msulliv2** [egingric/2016-Racing-Game#78]
The first time I played this, I thought the rubble ahead was an obstacle and that I had to go through the rocks to the left. Sometimes we're able to drive on terrain that appears that low, so I was trying to before I accidentally hit the rubble and it exploded. 
![chand2](https://cloud.githubusercontent.com/assets/18143256/14209298/82360f08-f7f1-11e5-9391-e9a5c9e042c5.JPG)

**Comment by ghost** [comment]
got rid of that
