### ISSUE TITLE
Collison on fire?

### ISSUE THREAD

**Issue by brouth** [egingric/2016-Racing-Game#91]
Theres a kill trigger when you go next to the fire and it's weird.
![myles](https://cloud.githubusercontent.com/assets/18143258/14209744/91a46a0a-f7f3-11e5-949f-a02d9bbfbea8.JPG)

**Comment by egingric** [comment]
Make sure you use Eric's Death function to kill the player otherwise it looks like they teleported.

**Comment by Msulliv2** [comment]
Resolved and Death function added
@brouth 
@egingric
