### ISSUE TITLE
Don't let me roll down hill at start

### ISSUE THREAD

**Issue by egingric** [egingric/2016-Racing-Game#93]

**Comment by Msulliv2** [comment]
I believe I corrected the issue, but is there a way to test every spawn point manually? I always start at the same one every time I play.

@egingric

**Comment by egingric** [comment]
Start four player split screen over and over again to test. It picks a random point every time.

**Comment by Msulliv2** [comment]
Repositioned all the start points and tested free of rolling

@egingric
