### ISSUE TITLE
No texture

### ISSUE THREAD

**Issue by sbaldwi1** [egingric/2016-Racing-Game#97]
Maybe this is just a texture I don't have on my drive but just in case you forgot to texture it... 
![miles](https://cloud.githubusercontent.com/assets/18143255/14209882/61242248-f7f4-11e5-9c2a-d6a1a3cbb4e8.PNG)

**Comment by Msulliv2** [comment]
I can't find this anywhere. Could you check to see if it occurs again? or just be a bit more specific about the location? This picture is extremely vague/dutch
@sbaldwi1
