### ISSUE TITLE
Stretched UVs on rock

### ISSUE THREAD

**Issue by brouth** [egingric/2016-Racing-Game#98]
Just need to redo this rock and it'll be fine.
![myles3](https://cloud.githubusercontent.com/assets/18143258/14209900/796aaee4-f7f4-11e5-92d3-f433f97f1073.JPG)

**Comment by Msulliv2** [comment]
![correct](https://cloud.githubusercontent.com/assets/18143256/14285354/2317efca-fb19-11e5-98c6-234861804f23.jpg)

Added some ivy instead. 
@brouth
